<?php

/**
 * Mô hình kinh doanh (v1.3.0) — Rót hỗ trợ CÙNG MỘT bộ nghiệp vụ (bán hàng,
 * kho, ca làm, báo cáo, sổ doanh thu...) cho nhiều loại hình khác nhau. File
 * này chỉ đổi CHỮ và ICON hiển thị cho đúng ngành hàng, KHÔNG đổi logic —
 * xem App\Services\BusinessTypeCatalog và Location::businessTerms().
 *
 * 'cafe', 'food', 'salon' là các mô hình đã kiểm chứng phù hợp với nghiệp vụ
 * hiện có: bán trực tiếp/mang đi, không quản lý theo bàn, không cần đặt lịch
 * hẹn trước. 'other' dùng cho mô hình chưa liệt kê — chủ quán tự đặt 1 từ gọi
 * tên đơn vị bán (VD: "suất ăn", "gói dịch vụ"), các câu còn lại được ghép
 * lại từ đúng từ đó (xem BusinessTypeCatalog::composeOther()).
 *
 * Thêm 1 mô hình mới: chỉ cần thêm 1 phần tử vào mảng 'types' dưới đây, không
 * cần sửa code nơi khác.
 */
return [
    'default' => 'cafe',

    'types' => [
        'cafe' => [
            'name' => 'Xe cà phê',
            'description' => 'Cà phê, trà sữa, nước ép, sinh tố...',
            'select_icon' => 'fa-mug-hot',
            'app_icon' => 'fa-mug-hot',
            'order_tab_icon' => 'fa-mug-saucer',
            'menu_icon' => 'fa-book-open',
            'menu_label' => 'Thực đơn',
            'menu_page_title' => 'Quản lý thực đơn',
            'catalog_singular' => 'món',
            'catalog_singular_cap' => 'Món',
            'modifier_label' => 'Tuỳ chọn món',
            'ingredient_label' => 'Kho nguyên liệu',
            'ingredient_singular' => 'nguyên liệu',
            'ingredient_name_placeholder' => 'Tên nguyên liệu',
            'ingredient_example_placeholder' => 'VD: Cà phê hạt, Sữa đặc, Ly nhựa L',
            'locations_label' => 'Các xe cà phê',
            'location_singular' => 'xe cà phê',
            'locations_icon' => 'fa-shop',
            'add_location_label' => 'Thêm xe cà phê mới',
            'location_name_placeholder' => 'Tên xe cà phê',
            'default_category_name' => 'Cà phê',
            'qr_toggle_label' => 'Đặt món qua QR',
            'qr_description' => 'Bật để khách quét mã QR dán tại xe, tự xem thực đơn và gửi yêu cầu gọi món.',
            'qr_save_button' => 'Lưu cài đặt đặt món qua QR',
            'qr_badge_title' => 'Yêu cầu gọi món từ khách (QR) đang chờ',
            'qr_page_tagline' => 'Xem thực đơn & gửi yêu cầu gọi món',
            'qr_submit_button' => 'Gửi yêu cầu gọi món',
            'quick_setup_description' => 'Sẽ tạo 2 món (Cà phê đá, Cà phê sữa) và 8 nguyên liệu trong kho.',
        ],

        'food' => [
            'name' => 'Quán ăn nhỏ',
            'description' => 'Cơm, bún, phở, bánh mì... bán tại quầy, không quản lý theo bàn',
            'select_icon' => 'fa-utensils',
            'app_icon' => 'fa-utensils',
            'order_tab_icon' => 'fa-bowl-food',
            'menu_icon' => 'fa-book-open',
            'menu_label' => 'Thực đơn',
            'menu_page_title' => 'Quản lý thực đơn',
            'catalog_singular' => 'món',
            'catalog_singular_cap' => 'Món',
            'modifier_label' => 'Tuỳ chọn món',
            'ingredient_label' => 'Kho nguyên liệu',
            'ingredient_singular' => 'nguyên liệu',
            'ingredient_name_placeholder' => 'Tên nguyên liệu',
            'ingredient_example_placeholder' => 'VD: Gạo, Thịt heo, Hộp mang đi',
            'locations_label' => 'Các quán ăn',
            'location_singular' => 'quán ăn',
            'locations_icon' => 'fa-shop',
            'add_location_label' => 'Thêm quán ăn mới',
            'location_name_placeholder' => 'Tên quán ăn',
            'default_category_name' => 'Món ăn',
            'qr_toggle_label' => 'Đặt món qua QR',
            'qr_description' => 'Bật để khách quét mã QR dán tại quán, tự xem thực đơn và gửi yêu cầu gọi món.',
            'qr_save_button' => 'Lưu cài đặt đặt món qua QR',
            'qr_badge_title' => 'Yêu cầu gọi món từ khách (QR) đang chờ',
            'qr_page_tagline' => 'Xem thực đơn & gửi yêu cầu gọi món',
            'qr_submit_button' => 'Gửi yêu cầu gọi món',
            'quick_setup_description' => 'Sẽ tạo sẵn vài món ăn mẫu và nguyên liệu trong kho.',
        ],

        'salon' => [
            'name' => 'Tiệm làm đẹp',
            'description' => 'Khách vãng lai, xếp lượt tại chỗ — chưa hỗ trợ đặt lịch hẹn trước',
            'select_icon' => 'fa-scissors',
            'app_icon' => 'fa-scissors',
            'order_tab_icon' => 'fa-scissors',
            'menu_icon' => 'fa-list-check',
            'menu_label' => 'Bảng giá dịch vụ',
            'menu_page_title' => 'Quản lý dịch vụ',
            'catalog_singular' => 'dịch vụ',
            'catalog_singular_cap' => 'Dịch vụ',
            'modifier_label' => 'Tuỳ chọn dịch vụ',
            'ingredient_label' => 'Kho vật tư',
            'ingredient_singular' => 'vật tư',
            'ingredient_name_placeholder' => 'Tên vật tư',
            'ingredient_example_placeholder' => 'VD: Dầu gội, Thuốc nhuộm, Khăn dùng 1 lần',
            'locations_label' => 'Các tiệm',
            'location_singular' => 'tiệm',
            'locations_icon' => 'fa-store',
            'add_location_label' => 'Thêm tiệm mới',
            'location_name_placeholder' => 'Tên tiệm',
            'default_category_name' => 'Dịch vụ',
            'qr_toggle_label' => 'Đặt dịch vụ qua QR',
            'qr_description' => 'Bật để khách quét mã QR dán tại tiệm, tự xem bảng giá và gửi yêu cầu dịch vụ muốn làm trong lúc chờ tới lượt.',
            'qr_save_button' => 'Lưu cài đặt đặt dịch vụ qua QR',
            'qr_badge_title' => 'Yêu cầu dịch vụ từ khách (QR) đang chờ',
            'qr_page_tagline' => 'Xem bảng giá & gửi yêu cầu dịch vụ',
            'qr_submit_button' => 'Gửi yêu cầu dịch vụ',
            'quick_setup_description' => 'Sẽ tạo sẵn vài dịch vụ mẫu và vật tư trong kho.',
        ],

        'other' => [
            'name' => 'Khác',
            'description' => 'Tự đặt tên cho đơn vị bán của bạn',
            'select_icon' => 'fa-store',
            'app_icon' => 'fa-store',
            'order_tab_icon' => 'fa-cart-shopping',
            'menu_icon' => 'fa-list-check',
            'menu_label' => 'Bảng giá',
            'menu_page_title' => 'Quản lý bảng giá',
            'catalog_singular' => 'mặt hàng',
            'catalog_singular_cap' => 'Mặt hàng',
            'modifier_label' => 'Tuỳ chọn',
            'ingredient_label' => 'Kho nguyên liệu',
            'ingredient_singular' => 'nguyên liệu',
            'ingredient_name_placeholder' => 'Tên nguyên liệu/vật tư',
            'ingredient_example_placeholder' => 'VD: nguyên liệu, vật tư tiêu hao',
            'locations_label' => 'Các địa điểm',
            'location_singular' => 'địa điểm',
            'locations_icon' => 'fa-store',
            'add_location_label' => 'Thêm địa điểm mới',
            'location_name_placeholder' => 'Tên địa điểm',
            'default_category_name' => 'Danh mục chính',
            'qr_toggle_label' => 'Đặt hàng qua QR',
            'qr_description' => 'Bật để khách quét mã QR, tự xem bảng giá và gửi yêu cầu.',
            'qr_save_button' => 'Lưu cài đặt đặt hàng qua QR',
            'qr_badge_title' => 'Yêu cầu từ khách (QR) đang chờ',
            'qr_page_tagline' => 'Xem bảng giá & gửi yêu cầu',
            'qr_submit_button' => 'Gửi yêu cầu',
            'quick_setup_description' => 'Sẽ tạo sẵn vài mặt hàng mẫu để bạn hình dung cách thiết lập.',
        ],
    ],
];
